from __future__ import annotations

import argparse
import json
import os
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify that all release-facing version declarations agree."
    )
    parser.add_argument(
        "--tag",
        help="Optional release tag to validate, for example v1.4.0. Tag pushes are detected automatically in GitHub Actions.",
    )
    args = parser.parse_args()

    cargo = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
    desktop_package = load_json(ROOT / "apps/desktop/package.json")
    desktop_lock = load_json(ROOT / "apps/desktop/package-lock.json")
    tauri_config = load_json(ROOT / "apps/desktop/src-tauri/tauri.conf.json")

    # The five declarations below all move by hand, but Cargo.lock's 13 workspace-member entries
    # can only be regenerated by cargo — and this machine has no cargo. A bump that forgets the
    # lock passes every declaration check here yet dies at CI step [8] `cargo check --locked`.
    # Measured 2026-10-01: a half-done 1.4.6 bump read green through this gate.
    workspace_version_for_lock = str(cargo["workspace"]["package"]["version"])
    member_names = set()
    for rel in cargo["workspace"].get("members", []):
        member_toml = ROOT / Path(str(rel)) / "Cargo.toml"
        if member_toml.exists():
            member_names.add(tomllib.loads(member_toml.read_text(encoding="utf-8"))["package"]["name"])
    src_tauri_name = tomllib.loads(
        (ROOT / "apps/desktop/src-tauri/Cargo.toml").read_text(encoding="utf-8")
    )["package"]["name"]
    member_names.add(src_tauri_name)
    stale_members = []
    seen_members = set()
    lock_text = (ROOT / "Cargo.lock").read_text(encoding="utf-8")
    for block in lock_text.split("[[package]]"):
        lines = block.splitlines()
        name = next((ln.split("=", 1)[1].strip().strip('"') for ln in lines if ln.startswith("name =")), None)
        ver = next((ln.split("=", 1)[1].strip().strip('"') for ln in lines if ln.startswith("version =")), None)
        if name in member_names and ver is not None:
            seen_members.add(name)
            if ver != workspace_version_for_lock:
                stale_members.append(f"{name}={ver}")
    never_in_lock = sorted(member_names - seen_members)
    if stale_members or never_in_lock:
        print("Cargo.lock workspace members are out of sync with the declared version:", file=sys.stderr)
        for entry in stale_members:
            print(f"  - stale {entry} (expected {workspace_version_for_lock})", file=sys.stderr)
        for name in never_in_lock:
            print(f"  - member missing from Cargo.lock: {name}", file=sys.stderr)
        print("  Fix: run `cargo update --workspace` where cargo exists, or revert the bump.", file=sys.stderr)
        return 1

    versions = {
        "Cargo workspace": str(cargo["workspace"]["package"]["version"]),
        "desktop package.json": str(desktop_package["version"]),
        "desktop package-lock.json": str(desktop_lock.get("version", "")),
        "desktop package-lock root package": str(
            desktop_lock.get("packages", {}).get("", {}).get("version", "")
        ),
        "Tauri config": str(tauri_config["version"]),
    }

    missing = [name for name, version in versions.items() if not version]
    if missing:
        print("Missing release version declarations:", file=sys.stderr)
        for name in missing:
            print(f"  - {name}", file=sys.stderr)
        return 1

    unique_versions = set(versions.values())
    if len(unique_versions) != 1:
        print("Release version declarations are inconsistent:", file=sys.stderr)
        for name, version in versions.items():
            print(f"  - {name}: {version}", file=sys.stderr)
        return 1

    version = next(iter(unique_versions))
    tag = args.tag
    if tag is None and os.environ.get("GITHUB_REF", "").startswith("refs/tags/"):
        tag = os.environ.get("GITHUB_REF_NAME")

    if tag:
        expected_tag = f"v{version}"
        if tag != expected_tag:
            print(
                f"Release tag mismatch: expected {expected_tag!r} from project version, got {tag!r}.",
                file=sys.stderr,
            )
            return 1

    print(f"Release version consistent: {version}")
    print(f"Cargo.lock workspace members in sync: {len(seen_members)}/{len(member_names)} at {version}")
    if tag:
        print(f"Release tag consistent: {tag}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
