#!/usr/bin/env python3
"""Generate project state from authoritative sources instead of hand-written prose.

Rationale (docs/REFERENCE_COMPARISON_PICGO_PICLIST.md discussion, piclist.md #29-#31):
`.ai/STATE.md` and `.ai/TASKS.md` drifted three ways apart because a human re-typed the same
facts into several files. Facts are now read from git / Cargo / package.json / tags here; only
narrative stays hand-written.

Two modes:
  --write   regenerate .ai/STATE.generated.json  (offline-safe: no network)
  --verify  fail if the committed JSON disagrees with what this checkout reports, or if a
            hand-maintained file contradicts a generated fact

Offline by design. The CI/release API facts are deliberately NOT stored here: they move on
their own and would reintroduce the exact staleness this generator exists to remove. Read them
live with `--show-live`.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / ".ai" / "STATE.generated.json"
SCHEMA_VERSION = 1


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace"
    ).stdout.strip()


def canonical_repo_name() -> str | None:
    """Ask GitHub which name it now serves. Returns None when offline or unauthenticated-blocked."""
    try:
        import urllib.request

        request = urllib.request.Request(
            "https://api.github.com/repositories/1376738679",
            headers={"User-Agent": "mirror-cloud-project-state"},
        )
        with urllib.request.urlopen(request, timeout=8) as response:
            return json.loads(response.read().decode("utf-8")).get("full_name")
    except Exception:  # noqa: BLE001 - offline is a supported mode; absence must not look like a pass
        return None


def local_facts() -> dict:
    head = git("rev-parse", "HEAD")
    cargo = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
    desktop = json.loads((ROOT / "apps" / "desktop" / "package.json").read_text(encoding="utf-8"))
    tauri = json.loads(
        (ROOT / "apps" / "desktop" / "src-tauri" / "tauri.conf.json").read_text(encoding="utf-8")
    )
    members = [m for m in cargo["workspace"]["members"]]
    lock = (ROOT / "Cargo.lock").read_text(encoding="utf-8")
    lock_versions = set(re.findall(r'name = "(mirror-cloud-[a-z-]|publisher-)[^"]*"', lock))
    del lock_versions  # reconciliation is owned by check_release_version.py; not duplicated here

    remote_url = git("remote", "get-url", "origin")
    repo = re.sub(r"^https://[^@]*@", "", remote_url)
    repo = re.sub(r"\.git$", "", repo)
    repo = repo.split("github.com/")[-1] if "github.com/" in repo else repo

    dirty = bool(git("status", "--porcelain"))
    # ls-remote lines are "<sha>\trefs/tags/<name>" (annotated tags add a second "^{}" line).
    # Strip through the ref prefix before matching: matching the raw line makes every name fail
    # the regex and silently reports "no tags" - a zero that means "the gauge is blind".
    tag_names = {
        re.sub(r"^.*refs/tags/", "", line.split("\t")[-1]).replace("^{}", "")
        for line in git("ls-remote", "--tags", "origin").splitlines()
        if line.strip()
    }
    versioned = sorted(t for t in tag_names if re.fullmatch(r"v\d+\.\d+\.\d+", t))

    def vkey(tag: str) -> tuple[int, ...]:
        return tuple(int(p) for p in tag[1:].split("."))

    newest_tag = max(versioned, key=vkey) if versioned else None

    return {
        "schema": SCHEMA_VERSION,
        "_comment": "Generated by scripts/project_state.py --write. Do not hand-edit facts here.",
        "repository": repo,
        "branch": git("rev-parse", "--abbrev-ref", "HEAD"),
        "head_sha": head[:7],
        "head_full": head,
        "head_subject": git("log", "-1", "--format=%s"),
        "working_tree_dirty": dirty,
        "version_declared": {
            "cargo_workspace": str(cargo["workspace"]["package"]["version"]),
            "desktop_package_json": desktop["version"],
            "tauri_conf": tauri["version"],
        },
        "workspace_members": len(members),
        "newest_version_tag_on_origin": newest_tag,
        "commit_count_since_newest_tag": (
            int(git("rev-list", "--count", f"{newest_tag}..HEAD")) if newest_tag else None
        ),
        "hand_maintained_files": [".ai/STATE.md", ".ai/TASKS.md", "README.md"],
    }


LIVE_HINT = (
    "Live facts are intentionally not persisted (they go stale). Read them at the moment you need "
    "them:\n"
    "  curl -s https://api.github.com/repositories/{id}/actions/runs?per_page=1\n"
    "  curl -s https://api.github.com/repos/{repo}/releases/latest\n"
)


def verify(facts: dict) -> list[str]:
    """Alarm when a hand-written file states a fact that contradicts the generated one."""
    problems: list[str] = []

    if facts["working_tree_dirty"]:
        # Advisory, not drift: while regenerating this file is the only pending change, "dirty" is
        # true by construction and can never be recorded clean - as a blocking problem it would be a
        # permanently-red fixture. Printed so a human sees it; excluded from the exit code.
        print("NOTE working tree is dirty (generated state describes HEAD, not these edits)")

    declared = set(facts["version_declared"].values())
    if len(declared) != 1:
        problems.append(f"version declarations disagree among themselves: {facts['version_declared']}")
    version = next(iter(declared))

    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    m = re.search(r"当前开发线：\*\*v([0-9.]+)", readme)
    if m and m.group(1) != version:
        problems.append(f"README.md:7 says development line v{m.group(1)} but code declares {version}")

    clone_line = re.search(r"git clone https://github\.com/([^\s/]+)/([^\s.]+)", readme)
    if clone_line:
        cloned = f"{clone_line.group(1)}/{clone_line.group(2)}"
        # Compare against the canonical API name, not `git remote get-url`: origin itself still
        # carries the pre-rename path (pushes work via GitHub's redirect), so origin-vs-README
        # would agree while both are wrong. The API is the only independent witness here.
        canonical = canonical_repo_name()
        if canonical is None:
            # Degraded, and origin is NOT a valid substitute here: the local remote still carries
            # the pre-rename path (pushes work through GitHub's redirect), so falling back to it
            # would blame a correctly-updated README. Skip with a visible note instead.
            print("SKIP clone-URL check (GitHub API unreachable; origin is not a trustworthy witness)")
        elif cloned != canonical:
            problems.append(f"README.md clone URL says {cloned} but GitHub reports {canonical}")

    state = ROOT / ".ai" / "STATE.md"
    if state.exists():
        body = state.read_text(encoding="utf-8")
        for pat, label in (
            (r"`([0-9a-f]{7})` = CI run", "dev baseline sha"),
            (r"版本声明：([0-9.]+)", "version declaration"),
        ):
            found = re.search(pat, body)
            if not found:
                continue
            value = found.group(1)
            if label == "dev baseline sha" and value != facts["head_sha"]:
                problems.append(
                    f".ai/STATE.md pins dev baseline {value} but HEAD is {facts['head_sha']} "
                    "(the drift this generator exists to prevent)"
                )
            if label == "version declaration" and value != version:
                problems.append(f".ai/STATE.md declares version {value} but code says {version}")

    if GENERATED.exists():
        committed = json.loads(GENERATED.read_text(encoding="utf-8"))
        # working_tree_dirty can never be recorded truthfully while the only uncommitted change is
        # this very file, so it is excluded from the staleness comparison; it still alarms on its own.
        volatile = {"head_subject", "working_tree_dirty"}
        stale = [k for k, v in committed.items() if k not in volatile and facts.get(k) != v]
        if stale:
            problems.append(f"{GENERATED.name} is stale for keys {stale}; re-run --write")
    else:
        problems.append(f"{GENERATED.name} missing; run scripts/project_state.py --write")

    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="regenerate .ai/STATE.generated.json")
    parser.add_argument("--verify", action="store_true", help="fail if committed state or prose contradicts facts")
    parser.add_argument("--show-live", action="store_true", help="print where to read live CI/Release facts")
    args = parser.parse_args()

    facts = local_facts()

    if args.show_live:
        print(LIVE_HINT.format(id="1376738679", repo=facts["repository"]))

    if args.write:
        GENERATED.write_text(json.dumps(facts, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"PROJECT_STATE wrote {GENERATED.relative_to(ROOT)}")
        print(json.dumps(facts, indent=2, ensure_ascii=False))
        return 0

    if args.verify:
        problems = verify(facts)
        print(f"PROJECT_STATE_VERIFY facts={len(facts)} problems={len(problems)}")
        for p in problems:
            print(f"FAIL {p}")
        if problems:
            print("PROJECT_STATE_VERIFY: DRIFT DETECTED")
            return 1
        print("PROJECT_STATE_VERIFY: hand-written prose agrees with generated facts")
        return 0

    print(json.dumps(facts, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
